require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./src/model/product');

const connectDB = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('MongoDB Connected for seeding...');
    } catch (error) {
        console.error('Database connection error:', error);
        process.exit(1);
    }
};

const moreProducts = [
    // More Electronics
    { name: "OnePlus 12 5G", gemProductId: "GEM024", gemPrice: 64999, description: "OnePlus 12 5G with Snapdragon 8 Gen 3, 12GB RAM, 256GB Storage", category: "Electronics", brand: "OnePlus", images: [{ public_id: "oneplus12", url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=300&h=300&fit=crop" }], specs: new Map([["Display", "6.82-inch AMOLED"], ["Processor", "Snapdragon 8 Gen 3"], ["RAM", "12GB"], ["Storage", "256GB"], ["Camera", "50MP Triple Camera"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/oneplus12", price: 68999, discount: 6, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/oneplus12", price: 67499, discount: 4, isAvailable: true }] },
    { name: "Sony WH-1000XM5 Headphones", gemProductId: "GEM025", gemPrice: 29990, description: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones", category: "Electronics", brand: "Sony", images: [{ public_id: "sonyheadphones", url: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=300&h=300&fit=crop" }], specs: new Map([["Type", "Over-Ear"], ["Connectivity", "Bluetooth 5.2"], ["Battery", "30 hours"], ["Noise Cancellation", "Yes"], ["Weight", "250g"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/sonyheadphones", price: 32990, discount: 9, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/sonyheadphones", price: 31990, discount: 6, isAvailable: true }] },
    
    // More Appliances
    { name: "Voltas 1.5 Ton 3 Star AC", gemProductId: "GEM026", gemPrice: 32990, description: "Voltas 1.5 Ton 3 Star Split Inverter AC with Copper Condenser", category: "Appliances", brand: "Voltas", images: [{ public_id: "voltasac", url: "https://images.unsplash.com/photo-1585909695284-32d2985ac9c0?w=300&h=300&fit=crop" }], specs: new Map([["Capacity", "1.5 Ton"], ["Type", "Split AC"], ["Energy Rating", "3 Star"], ["Compressor", "Inverter"], ["Warranty", "1 Year"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/voltasac", price: 36990, discount: 10, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/voltasac", price: 35490, discount: 7, isAvailable: true }] },
    { name: "IFB 30L Microwave Oven", gemProductId: "GEM027", gemPrice: 14990, description: "IFB 30L Convection Microwave Oven with Auto Cook Menu", category: "Appliances", brand: "IFB", images: [{ public_id: "ifbmicrowave", url: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=300&h=300&fit=crop" }], specs: new Map([["Capacity", "30 Liters"], ["Type", "Convection"], ["Power", "2900W"], ["Auto Cook", "101 Menus"], ["Warranty", "1 Year"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/ifbmicrowave", price: 16990, discount: 11, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/ifbmicrowave", price: 15990, discount: 6, isAvailable: true }] },
    
    // More Clothing
    { name: "Adidas Originals Hoodie", gemProductId: "GEM028", gemPrice: 3499, description: "Adidas Originals Men's Trefoil Hoodie - Black", category: "Clothing", brand: "Adidas", images: [{ public_id: "adidashoodie", url: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=300&h=300&fit=crop" }], specs: new Map([["Material", "70% Cotton, 30% Polyester"], ["Fit", "Regular Fit"], ["Color", "Black"], ["Sizes", "S, M, L, XL, XXL"], ["Care", "Machine Wash"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/adidashoodie", price: 3999, discount: 12, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/adidashoodie", price: 3799, discount: 8, isAvailable: true }] },
    { name: "Zara Women's Blazer", gemProductId: "GEM029", gemPrice: 4999, description: "Zara Women's Formal Blazer - Navy Blue", category: "Clothing", brand: "Zara", images: [{ public_id: "zarablaze", url: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=300&h=300&fit=crop" }], specs: new Map([["Material", "Polyester Blend"], ["Fit", "Slim Fit"], ["Color", "Navy Blue"], ["Sizes", "XS, S, M, L, XL"], ["Occasion", "Formal"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/zarablaze", price: 5799, discount: 13, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/zarablaze", price: 5499, discount: 9, isAvailable: true }] },
    
    // More Furniture
    { name: "Urban Ladder Study Table", gemProductId: "GEM030", gemPrice: 12999, description: "Urban Ladder Wooden Study Table with Drawer", category: "Furniture", brand: "Urban Ladder", images: [{ public_id: "studytable", url: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=300&h=300&fit=crop" }], specs: new Map([["Material", "Engineered Wood"], ["Color", "Walnut Brown"], ["Dimensions", "120x60x75 cm"], ["Storage", "1 Drawer"], ["Assembly", "Required"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/studytable", price: 14999, discount: 13, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/studytable", price: 13999, discount: 7, isAvailable: true }] },
    { name: "Nilkamal Plastic Chair Set of 4", gemProductId: "GEM031", gemPrice: 3999, description: "Nilkamal Plastic Chairs Set of 4 - Multi Color", category: "Furniture", brand: "Nilkamal", images: [{ public_id: "nilkamalchair", url: "https://images.unsplash.com/photo-1503602642458-232111445657?w=300&h=300&fit=crop" }], specs: new Map([["Material", "High Quality Plastic"], ["Color", "Multi Color"], ["Weight Capacity", "100 kg per chair"], ["Quantity", "4 Chairs"], ["Warranty", "1 Year"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/nilkamalchair", price: 4599, discount: 13, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/nilkamalchair", price: 4299, discount: 7, isAvailable: true }] },
    
    // More Office Supplies
    { name: "Canon Pixma G3000 Printer", gemProductId: "GEM032", gemPrice: 12500, description: "Canon Pixma G3000 All-in-One Wireless Ink Tank Printer", category: "Office Supplies", brand: "Canon", images: [{ public_id: "canonprinter", url: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=300&h=300&fit=crop" }], specs: new Map([["Type", "Ink Tank"], ["Functions", "Print, Scan, Copy"], ["Connectivity", "Wi-Fi, USB"], ["Print Speed", "8.8 ipm"], ["Warranty", "1 Year"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/canonprinter", price: 13990, discount: 10, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/canonprinter", price: 13490, discount: 7, isAvailable: true }] },
    
    // More IT Peripherals
    { name: "Dell KB216 Wired Keyboard", gemProductId: "GEM033", gemPrice: 599, description: "Dell KB216 Wired Multimedia Keyboard - Black", category: "IT Peripherals", brand: "Dell", images: [{ public_id: "dellkeyboard", url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&h=300&fit=crop" }], specs: new Map([["Type", "Wired"], ["Connectivity", "USB"], ["Layout", "QWERTY"], ["Color", "Black"], ["Warranty", "1 Year"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/dellkeyboard", price: 699, discount: 14, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/dellkeyboard", price: 649, discount: 8, isAvailable: true }] },
    { name: "Seagate 2TB External HDD", gemProductId: "GEM034", gemPrice: 5499, description: "Seagate Backup Plus Slim 2TB External Hard Drive", category: "IT Peripherals", brand: "Seagate", images: [{ public_id: "seagatehdd", url: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=300&h=300&fit=crop" }], specs: new Map([["Capacity", "2TB"], ["Type", "Portable HDD"], ["Connectivity", "USB 3.0"], ["Speed", "5400 RPM"], ["Warranty", "2 Years"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/seagatehdd", price: 6199, discount: 11, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/seagatehdd", price: 5899, discount: 7, isAvailable: true }] },
    
    // More Sports
    { name: "Yonex Badminton Racket", gemProductId: "GEM035", gemPrice: 2999, description: "Yonex Nanoray Light 18i Graphite Badminton Racket", category: "Sports", brand: "Yonex", images: [{ public_id: "yonexracket", url: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=300&h=300&fit=crop" }], specs: new Map([["Material", "Graphite"], ["Weight", "73g"], ["Grip Size", "G4"], ["String Tension", "20-28 lbs"], ["Cover", "Included"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/yonexracket", price: 3499, discount: 14, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/yonexracket", price: 3299, discount: 9, isAvailable: true }] },
    { name: "Nivia Football Size 5", gemProductId: "GEM036", gemPrice: 799, description: "Nivia Storm Football Size 5 - Professional Quality", category: "Sports", brand: "Nivia", images: [{ public_id: "niviafootball", url: "https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?w=300&h=300&fit=crop" }], specs: new Map([["Size", "5"], ["Material", "PVC"], ["Type", "Match Ball"], ["Color", "White/Black"], ["Warranty", "6 Months"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/niviafootball", price: 949, discount: 15, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/niviafootball", price: 899, discount: 11, isAvailable: true }] },
    
    // More Toys
    { name: "Hot Wheels 20 Car Pack", gemProductId: "GEM037", gemPrice: 1999, description: "Hot Wheels 20 Die-Cast Cars Gift Pack", category: "Toys", brand: "Hot Wheels", images: [{ public_id: "hotwheels", url: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=300&h=300&fit=crop" }], specs: new Map([["Quantity", "20 Cars"], ["Scale", "1:64"], ["Age", "3+"], ["Material", "Die-Cast Metal"], ["Theme", "Assorted"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/hotwheels", price: 2399, discount: 16, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/hotwheels", price: 2199, discount: 9, isAvailable: true }] },
    { name: "Barbie Dreamhouse Playset", gemProductId: "GEM038", gemPrice: 8999, description: "Barbie Dreamhouse Playset with 8 Rooms and Accessories", category: "Toys", brand: "Barbie", images: [{ public_id: "barbiedreamhouse", url: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=300&h=300&fit=crop" }], specs: new Map([["Rooms", "8"], ["Height", "3 feet"], ["Age", "3+"], ["Accessories", "70+ pieces"], ["Assembly", "Required"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/barbiedreamhouse", price: 10499, discount: 14, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/barbiedreamhouse", price: 9999, discount: 10, isAvailable: true }] },
    
    // More Automotive
    { name: "Michelin Car Tyres Set of 4", gemProductId: "GEM039", gemPrice: 24000, description: "Michelin Primacy 4 Car Tyres 195/65 R15 - Set of 4", category: "Automotive", brand: "Michelin", images: [{ public_id: "michelintyres", url: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=300&h=300&fit=crop" }], specs: new Map([["Size", "195/65 R15"], ["Quantity", "4 Tyres"], ["Type", "Tubeless"], ["Warranty", "5 Years"], ["Load Index", "91V"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/michelintyres", price: 26800, discount: 10, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/michelintyres", price: 25600, discount: 6, isAvailable: true }] },
    
    // More Baby
    { name: "Chicco Baby Stroller", gemProductId: "GEM040", gemPrice: 8999, description: "Chicco Lite Way 3 Baby Stroller with Canopy", category: "Baby", brand: "Chicco", images: [{ public_id: "chiccostroller", url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=300&h=300&fit=crop" }], specs: new Map([["Weight Capacity", "15 kg"], ["Folding", "Compact"], ["Canopy", "Adjustable"], ["Wheels", "4 Wheels"], ["Warranty", "1 Year"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/chiccostroller", price: 10499, discount: 14, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/chiccostroller", price: 9999, discount: 10, isAvailable: true }] },
    { name: "Johnson's Baby Care Set", gemProductId: "GEM041", gemPrice: 599, description: "Johnson's Baby Care Gift Set with 5 Products", category: "Baby", brand: "Johnson's", images: [{ public_id: "johnsonbaby", url: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=300&h=300&fit=crop" }], specs: new Map([["Products", "5 Items"], ["Includes", "Shampoo, Lotion, Oil, Soap, Powder"], ["Volume", "Combo Pack"], ["Age", "0+ months"], ["Dermatologist Tested", "Yes"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/johnsonbaby", price: 699, discount: 14, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/johnsonbaby", price: 649, discount: 8, isAvailable: true }] },
    
    // More Grocery
    { name: "Tata Tea Premium 1kg", gemProductId: "GEM042", gemPrice: 450, description: "Tata Tea Premium Black Tea 1kg Pack", category: "Grocery", brand: "Tata", images: [{ public_id: "tatatea", url: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=300&h=300&fit=crop" }], specs: new Map([["Weight", "1 kg"], ["Type", "Black Tea"], ["Packaging", "Pouch"], ["Shelf Life", "24 Months"], ["Origin", "India"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/tatatea", price: 520, discount: 13, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/tatatea", price: 490, discount: 8, isAvailable: true }] },
    { name: "Aashirvaad Atta 10kg", gemProductId: "GEM043", gemPrice: 420, description: "Aashirvaad Whole Wheat Atta 10kg Pack", category: "Grocery", brand: "Aashirvaad", images: [{ public_id: "aashirvaadatta", url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&h=300&fit=crop" }], specs: new Map([["Weight", "10 kg"], ["Type", "Whole Wheat"], ["Packaging", "Bag"], ["Shelf Life", "6 Months"], ["100% MP Wheat", "Yes"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/aashirvaadatta", price: 480, discount: 12, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/aashirvaadatta", price: 450, discount: 7, isAvailable: true }] },
    
    // More Health & Beauty
    { name: "Nivea Men Face Wash", gemProductId: "GEM044", gemPrice: 199, description: "Nivea Men Dark Spot Reduction Face Wash 100g", category: "Health & Beauty", brand: "Nivea", images: [{ public_id: "niveafacewash", url: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=300&h=300&fit=crop" }], specs: new Map([["Volume", "100g"], ["Type", "Face Wash"], ["For", "Men"], ["Benefits", "Dark Spot Reduction"], ["Dermatologist Tested", "Yes"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/niveafacewash", price: 239, discount: 16, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/niveafacewash", price: 219, discount: 9, isAvailable: true }] },
    { name: "Maybelline Lipstick", gemProductId: "GEM045", gemPrice: 349, description: "Maybelline New York SuperStay Matte Ink Lipstick", category: "Health & Beauty", brand: "Maybelline", images: [{ public_id: "maybellinelipstick", url: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=300&h=300&fit=crop" }], specs: new Map([["Type", "Liquid Lipstick"], ["Finish", "Matte"], ["Longevity", "16 Hours"], ["Shade", "Voyager"], ["Volume", "5ml"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/maybellinelipstick", price: 419, discount: 16, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/maybellinelipstick", price: 389, discount: 10, isAvailable: true }] },
    
    // More Home
    { name: "Prestige Induction Cooktop", gemProductId: "GEM046", gemPrice: 2499, description: "Prestige PIC 20.0 1600-Watt Induction Cooktop", category: "Home", brand: "Prestige", images: [{ public_id: "prestigeinduction", url: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=300&h=300&fit=crop" }], specs: new Map([["Power", "1600W"], ["Type", "Induction"], ["Preset Menus", "8"], ["Timer", "3 Hours"], ["Warranty", "1 Year"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/prestigeinduction", price: 2899, discount: 13, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/prestigeinduction", price: 2699, discount: 7, isAvailable: true }] },
    { name: "Cello Water Bottle Set", gemProductId: "GEM047", gemPrice: 399, description: "Cello H2O Unbreakable Bottle Set of 4 - 1 Liter Each", category: "Home", brand: "Cello", images: [{ public_id: "cellobottle", url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop" }], specs: new Map([["Capacity", "1 Liter Each"], ["Quantity", "4 Bottles"], ["Material", "Plastic"], ["Type", "Unbreakable"], ["Color", "Assorted"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/cellobottle", price: 479, discount: 16, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/cellobottle", price: 449, discount: 11, isAvailable: true }] },
    
    // More Jewellery
    { name: "Malabar Gold Earrings", gemProductId: "GEM048", gemPrice: 15000, description: "Malabar Gold 22K Yellow Gold Stud Earrings for Women", category: "Jewellery", brand: "Malabar Gold", images: [{ public_id: "malabargoldearrings", url: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=300&h=300&fit=crop" }], specs: new Map([["Purity", "22K Gold"], ["Weight", "3 grams"], ["Type", "Stud Earrings"], ["Gender", "Women"], ["Design", "Traditional"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/malabargoldearrings", price: 16500, discount: 9, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/malabargoldearrings", price: 15900, discount: 6, isAvailable: true }] },
    
    // More Office
    { name: "Wipro Garnet LED Desk Lamp", gemProductId: "GEM049", gemPrice: 899, description: "Wipro Garnet 6W LED Table Lamp with Adjustable Arm", category: "Office", brand: "Wipro", images: [{ public_id: "wiprolamp", url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=300&h=300&fit=crop" }], specs: new Map([["Power", "6W LED"], ["Type", "Desk Lamp"], ["Adjustable", "Yes"], ["Color Temperature", "6500K"], ["Warranty", "1 Year"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/wiprolamp", price: 1099, discount: 18, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/wiprolamp", price: 999, discount: 10, isAvailable: true }] },
    { name: "Classmate Notebook Pack", gemProductId: "GEM050", gemPrice: 250, description: "Classmate Single Line Notebooks 172 Pages - Pack of 6", category: "Office", brand: "Classmate", images: [{ public_id: "classmatenotebook", url: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=300&h=300&fit=crop" }], specs: new Map([["Pages", "172 per notebook"], ["Quantity", "6 Notebooks"], ["Type", "Single Line"], ["Size", "297 x 210 mm"], ["Paper Quality", "Premium"]]), marketplacePrices: [{ marketplace: "Amazon", productUrl: "https://amazon.in/classmatenotebook", price: 299, discount: 16, isAvailable: true }, { marketplace: "Flipkart", productUrl: "https://flipkart.com/classmatenotebook", price: 279, discount: 10, isAvailable: true }] }
];

const seedDatabase = async () => {
    try {
        await connectDB();
        
        const products = await Product.insertMany(moreProducts);
        console.log(`✅ ${products.length} additional products added successfully!`);
        
        const totalProducts = await Product.countDocuments();
        console.log(`📦 Total products in database: ${totalProducts}`);
        
        const categories = await Product.distinct('category');
        console.log('\n📊 Products by category:');
        for (const cat of categories) {
            const count = await Product.countDocuments({ category: cat });
            console.log(`  - ${cat}: ${count} products`);
        }
        
        process.exit(0);
    } catch (error) {
        console.error('Seeding error:', error);
        process.exit(1);
    }
};

seedDatabase();
